version: '3'
services:
  redis:
    image: 'redis:5.0.5-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
  
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  app:
    depends_on:
      - 'redis'
      - 'postgres'
    build: .
    command: bash start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
volumes:
  redis:
  gems:
  postgres: