version: '3'
services:
  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  trading-api:
    depends_on:
      - 'postgres'
    build: .
    image: tobiasandre/trading-api
    command: bash start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@postgres
      
volumes:
  gems:
  postgres: