version: '3'
services:
  redis:
    image: 'redis:5.0.5-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:12'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  trading-api:
    depends_on:
      - 'redis'
      - 'postgres'
    build: .
    image: tobiasandre/trading-api
    command: bash start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@postgres
      REDIS_URL: redis://redis:6379/1
      
volumes:
  gems:
  redis:
  postgres: